config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index

    @expenses = Expense.all
    get_current_daily_expenses


  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    @expense.update({
      expense_type: @expense.expense_type,
      expense_content: @expense.expense_content,
      expense_cost: @expense.expense_cost,
      expense_date: Date.today,
      purchaser_name: @expense.purchaser_name
    })

    # @expense.update({ expense_type: @expense.expense_type,
    #                   expense_content: @expense.expense_content,
    #                   expense_cost: @expense.expense_cost,
    #                   expense_date: Date.today,
    #                   purchaser_name: @expense.purchaser_name,
    #                   start_time: @expense.start_time})



    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def get_current_daily_expenses
    @current_daily_expenses = Expense.all.where({:expense_date => Date.today})
    @daily_total = 0
    @current_daily_expenses.each do |expense|
      @daily_total += expense.expense_cost
    end
  end

  def get_weekly_expenses
    #@weekly_expenses = Expense.all.where
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def expense_params
    params.require(:expense).permit(:start_time, :expense_type, :expense_date, :expense_content, :expense_cost, :purchaser_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(expense) do |f| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expense_type %>
    <%= f.text_field :expense_type %>
  </div>

  <div class="field">
    <%= f.label :expense_content %>
    <%= f.text_area :expense_content %>
  </div>

  <div class="field">
    <%= f.label :expense_cost %>
    <%= f.text_field :expense_cost %>
  </div>

  <div class="field">
    <%= f.label :purchaser_name %>
    <%= f.text_field :purchaser_name %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="row">
  <div class="four columns">


    <h1 style="font-size: 1.9em; color: #1cb531;">expenseLog</h1>


    <%= link_to 'Log New Expense', new_expense_path, class: "button" %>


  </div>
  <div class="eight columns">
<h5>Purchases made today</h5>
<table>
  <thead>
    <tr>

      <th>purchase</th>
      <th>$$$</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @current_daily_expenses.each do |expense| %>
      <tr>
        <td><%= expense.expense_type %></td>

        <td><span style="color:green">$</span> <%= expense.expense_cost %></td>
        <td><%= expense.purchaser_name %></td>



      </tr>
    <% end %>
  </tbody>
</table>
<h5><b>Stats</b></h5>
Total cost for today: <span style="color:green">$</span> <%= @daily_total %><br>
Total cost this week:<br>
Total cost this month:
<br>


<p>
  by <a href="#">@tristan_ag</a>
</p>
</div>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expense type:</strong>
  <%= @expense.expense_type %>
</p>

<p>
  <strong>Expense content:</strong>
  <%= @expense.expense_content %>
</p>

<p>
  <strong>Expense cost:</strong>
  <%= @expense.expense_cost %>
</p>

<p>
  <strong>Purchaser name:</strong>
  <%= @expense.purchaser_name %>
</p>



<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <footer>

    </footer>
  </body>
</html>